import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";
import createIntlMiddleware from "next-intl/middleware";
import { NextResponse } from "next/server";
import { routing } from "@/i18n/routing";

const intl = createIntlMiddleware(routing);

// Routes that next-intl is responsible for: locale-prefixed paths AND bare
// un-prefixed paths that map to a localised route (so /pricing redirects to
// /en/pricing). Bare `/` is NOT in this matcher — it's owned by app/page.tsx
// which renders the welcome splash for first-time visitors and redirects
// returning visitors to /<their-locale> server-side.
const isLocaleScopedRoute = createRouteMatcher([
  "/(en|hi)",
  "/(en|hi)/(.*)",
  "/pricing",
  "/library(.*)",
]);

const isPublicRoute = createRouteMatcher([
  "/",
  "/(en|hi)",
  "/(en|hi)/pricing",
  "/(en|hi)/library(.*)",
  // Bare un-prefixed marketing paths must be public so intl can redirect them
  // to the right /<locale>/... — without this, the auth check rejects them.
  "/pricing",
  "/library(.*)",
  "/sign-in(.*)",
  "/sign-up(.*)",
  // /post-signup is reached during Clerk's redirect after sign-up. Marked public
  // so the middleware doesn't race Clerk's session-cookie write; the page itself
  // gates its work behind useUser().isLoaded && isSignedIn.
  "/post-signup",
  "/api/stripe/webhook",
  "/api/health",
  // /api/assets is exposed at the middleware level; the route handler enforces
  // its own allowlist (PUBLIC_KEY_PATTERN in app/api/assets/route.ts) and
  // requires Clerk auth for any key outside it.
  "/api/assets",
  // SEO pseudo-static files generated by app/robots.ts and app/sitemap.ts —
  // must be reachable to crawlers without auth.
  "/robots.txt",
  "/sitemap.xml",
]);

const isAdminRoute = createRouteMatcher(["/admin(.*)"]);

export default clerkMiddleware(async (auth, request) => {
  // Admin routes — need role verification (defence in depth with layout redirect).
  // AppStateProvider rewrites /en/home to /<userRecord.locale>/home for returning users;
  // new sign-ups go via /post-signup which dispatches to home or library:resume target.
  if (isAdminRoute(request)) {
    const { userId, sessionClaims } = await auth();
    const role = (sessionClaims?.metadata as Record<string, string> | undefined)
      ?.role;
    if (!userId || role !== "admin") {
      return NextResponse.redirect(new URL("/en/home", request.url));
    }
    // Admin auth passed — fall through to intl handler below so locale headers
    // are still set for downstream rendering of /<locale>/admin pages.
  }

  // Auth gate FIRST for protected routes — short-circuit before next-intl runs.
  // Public routes skip auth() entirely (no Clerk network round-trip).
  if (!isPublicRoute(request) && !isAdminRoute(request)) {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.redirect(new URL("/sign-in", request.url));
    }
  }

  // For locale-scoped routes, ALWAYS return next-intl's response. This is the
  // canonical Clerk + next-intl composition: intl needs to either redirect
  // (e.g. /pricing → /en/pricing) OR pass through with locale headers set for
  // downstream useTranslations / getMessages calls. Returning anything else
  // (or returning undefined) drops the locale signal and breaks client-side
  // translations.
  if (isLocaleScopedRoute(request)) {
    return intl(request);
  }
});

export const config = {
  matcher: [
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    "/(api|trpc)(.*)",
  ],
};
