/**
 * Shared client-side audio playback for Lists & Sentences (Phase 8.5).
 *
 * Audio for list items / sentences is resolved by `(current-language text,
 * current voice)` at play time — never stored as a per-item TTS path — so it
 * follows the active language + voice. Human recordings are a voice-independent
 * override that wins.
 *
 * Reuses the existing endpoints only — no duplicate generate/play logic:
 *   - `POST /api/tts`  → symbolstix → ttsCache → synthesise+cache (voice-aware,
 *                        writes the GLOBAL ttsCache, so a clip generated by one
 *                        user is reused by every other user with the same
 *                        (text, voice) — the cross-user match).
 *   - `GET  /api/assets?key=…` → 302-redirect to a signed R2 URL.
 *
 * iOS Safari note: `audio.play()` must run inside the user gesture. An `await`
 * before `.play()` breaks that chain, so:
 *   - `playKey()` is fully synchronous — use it for recordings and for cached
 *     audio whose `r2Key` was pre-resolved (e.g. via `ttsCache.checkMany`).
 *   - `playTts()` awaits `/api/tts` first — only for a genuinely-cold first tap
 *     (uncached text in this voice). The authoring "generate" signal pre-warms
 *     the cache so students rarely hit this path.
 */

/** Play an R2 key synchronously (gesture-safe). Returns the element so callers can stop it. */
export function playKey(r2Key: string): HTMLAudioElement {
  const audio = new Audio(`/api/assets?key=${encodeURIComponent(r2Key)}`);
  audio.play().catch(() => {});
  return audio;
}

/**
 * Resolve `(text, voiceId[, tone])` through /api/tts (cache hit, or synthesise
 * on a cold first tap) to an r2Key WITHOUT playing it. Use when the caller wants
 * to drive playback itself — e.g. to await the clip's `ended` event for stepped
 * playback.
 *
 * `tone` (Phase 15, Thread 2) selects the expressive Gemini path for the fluent
 * whole-utterance clip. Omitted/"neutral" = the existing cheap voice, unchanged.
 */
export async function resolveTtsKey(
  text: string,
  voiceId: string,
  tone?: string
): Promise<string | undefined> {
  const trimmed = text.trim();
  if (!trimmed) return undefined;
  try {
    const res = await fetch("/api/tts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        text: trimmed,
        voiceId,
        ...(tone && tone !== "neutral" ? { tone } : {}),
      }),
    });
    if (!res.ok) return undefined;
    const { r2Key } = (await res.json()) as { r2Key?: string };
    return r2Key ?? undefined;
  } catch {
    return undefined;
  }
}

/**
 * Resolve `(text, voiceId[, tone])` through /api/tts (cache hit, or synthesise
 * on a cold first tap) and play the result. Returns the resolved r2Key (or
 * undefined on failure). Use `playKey` instead when a pre-resolved key is
 * already in hand.
 */
export async function playTts(
  text: string,
  voiceId: string,
  tone?: string
): Promise<string | undefined> {
  const r2Key = await resolveTtsKey(text, voiceId, tone);
  if (!r2Key) return undefined;
  playKey(r2Key);
  return r2Key;
}
