/**
 * SentenceModule catalogue barrel (ADR-014 §1). AUTO-GENERATED by
 * scripts/export-library-modules.mjs — these JSON files are the git
 * backup/restore artifact for the libraryModules table, NOT the live source.
 * Regenerate by re-running the exporter, not by hand-editing.
 */

import type { SentenceModule } from "../_shared/types";

// ── Module imports ────────────────────────────────────────────────────────────
import everydayPhrases from "./everyday-phrases.json";
import expressingFeelings from "./expressing-feelings.json";
import goingPlaces from "./going-places.json";
import talkingAboutFood from "./talking-about-food.json";

// ── Catalogue map ─────────────────────────────────────────────────────────────
export const SENTENCE_MODULES: Record<string, SentenceModule> = {
  "everyday-phrases": everydayPhrases as unknown as SentenceModule,
  "expressing-feelings": expressingFeelings as unknown as SentenceModule,
  "going-places": goingPlaces as unknown as SentenceModule,
  "talking-about-food": talkingAboutFood as unknown as SentenceModule,
};
