/**
 * SentenceModule catalogue barrel (ADR-014 §1). AUTO-GENERATED by
 * scripts/convert-packs-to-modules.mjs and the curation publish route — add
 * modules by dropping <slug>.json here and re-running, not by hand-editing.
 */

import type { SentenceModule } from "../_shared/types";

// ── Module imports ────────────────────────────────────────────────────────────
import christmas from "./christmas.json";
import dinosaurs from "./dinosaurs.json";
import diwali from "./diwali.json";
import fun from "./fun.json";
import religion from "./religion.json";
import testPhrases from "./test-phrases.json";

// ── Catalogue map ─────────────────────────────────────────────────────────────
export const SENTENCE_MODULES: Record<string, SentenceModule> = {
  "christmas": christmas as SentenceModule,
  "dinosaurs": dinosaurs as SentenceModule,
  "diwali": diwali as SentenceModule,
  "fun": fun as SentenceModule,
  "religion": religion as SentenceModule,
  "test-phrases": testPhrases as SentenceModule,
};
