/**
 * Library pack catalogue barrel.
 *
 * Imports every `*.json` file in this directory and re-exports them as a
 * typed `LIBRARY_PACKS` map keyed by slug. Bundlers (Convex + Next.js) treat
 * the JSON imports as compile-time data, so this map ships with every deploy.
 *
 * **When adding a pack**: place the new `<slug>.json` file alongside this
 * barrel, then add one import line + one map entry below. Keep the map
 * keys + filenames + the file's `slug` field aligned.
 *
 * **When removing a pack**: delete the JSON file, remove the import and
 * the map entry. A pack is treated as "not in the catalogue" the moment
 * it's missing from `LIBRARY_PACKS`.
 *
 * Per ADR-010. This file is regenerated by `scripts/pack-migrate.mjs` on
 * migration, and edited by hand (or by the Phase 6 authoring API route)
 * thereafter.
 */

import type { LibraryPack } from "./types";

// ── Pack imports ────────────────────────────────────────────────────────────
import starter from "./_starter.json";
import christmas from "./christmas.json";
import dinosaurs from "./dinosaurs.json";
import diwali from "./diwali.json";
import fun from "./fun.json";
import religion from "./religion.json";
import vehicles from "./vehicles.json";

// ── Catalogue map ───────────────────────────────────────────────────────────

export const LIBRARY_PACKS: Record<string, LibraryPack> = {
  "_starter": starter as LibraryPack,
  "christmas": christmas as LibraryPack,
  "dinosaurs": dinosaurs as LibraryPack,
  "diwali": diwali as LibraryPack,
  "fun": fun as LibraryPack,
  "religion": religion as LibraryPack,
  "vehicles": vehicles as LibraryPack,
};

// ── Re-exports ──────────────────────────────────────────────────────────────

export type { LibraryPack } from "./types";
