/**
 * CategoryModule catalogue barrel (ADR-014 §1). AUTO-GENERATED by
 * scripts/convert-packs-to-modules.mjs and the curation publish route — add
 * modules by dropping <slug>.json here and re-running, not by hand-editing.
 */

import type { CategoryModule } from "../_shared/types";

// ── Module imports ────────────────────────────────────────────────────────────
import christmas from "./christmas.json";
import dinosaurs from "./dinosaurs.json";
import diwali from "./diwali.json";
import fun from "./fun.json";
import religion from "./religion.json";
import space from "./space.json";
import testActions from "./test-actions.json";
import vehicles from "./vehicles.json";

// ── Catalogue map ─────────────────────────────────────────────────────────────
export const CATEGORY_MODULES: Record<string, CategoryModule> = {
  "christmas": christmas as CategoryModule,
  "dinosaurs": dinosaurs as CategoryModule,
  "diwali": diwali as CategoryModule,
  "fun": fun as CategoryModule,
  "religion": religion as CategoryModule,
  "space": space as CategoryModule,
  "test-actions": testActions as CategoryModule,
  "vehicles": vehicles as CategoryModule,
};
