/**
 * Category-module catalogue barrel (ADR-014 §1).
 *
 * Imports every `*.json` category module in this directory and re-exports them
 * as a typed `CATEGORY_MODULES` map keyed by slug. Bundlers treat the JSON
 * imports as compile-time data, so this map ships with every deploy.
 *
 * **When adding a module**: drop `<slug>.json` alongside this barrel, then add
 * one import line + one map entry. Keep map key / filename / the file's `slug`
 * aligned. This file is regenerated by the curation publish route
 * (`/api/admin/pack-publish`) on every publish.
 *
 * Empty until the Phase 13 migration/curation seeds the first modules.
 */

import type { CategoryModule } from "../_shared/types";

// ── Module imports ────────────────────────────────────────────────────────────
// 13.2 throwaway fixture — remove once 13.4 curation seeds real modules.
import testActions from "./test-actions.json";

// ── Catalogue map ─────────────────────────────────────────────────────────────
export const CATEGORY_MODULES: Record<string, CategoryModule> = {
  "test-actions": testActions as CategoryModule,
};
