/**
 * CategoryModule catalogue barrel (ADR-014 §1). AUTO-GENERATED by
 * scripts/export-library-modules.mjs — these JSON files are the git
 * backup/restore artifact for the libraryModules table, NOT the live source.
 * Regenerate by re-running the exporter, not by hand-editing.
 */

import type { CategoryModule } from "../_shared/types";

// ── Module imports ────────────────────────────────────────────────────────────
import actions from "./actions.json";
import activities from "./activities.json";
import animals from "./animals.json";
import chat from "./chat.json";
import christmas from "./christmas.json";
import community from "./community.json";
import coreGeneral from "./core-general.json";
import coreJoiningWords from "./core-joining-words.json";
import coreLetters from "./core-letters.json";
import coreNumbers from "./core-numbers.json";
import corePositionWords from "./core-position-words.json";
import corePronouns from "./core-pronouns.json";
import coreTime from "./core-time.json";
import descriptions from "./descriptions.json";
import dinosaurs from "./dinosaurs.json";
import diwali from "./diwali.json";
import dropbarCore from "./dropbar-core.json";
import feelings from "./feelings.json";
import foodDrink from "./food-drink.json";
import fun from "./fun.json";
import health from "./health.json";
import home from "./home.json";
import nature from "./nature.json";
import numbers from "./numbers.json";
import people from "./people.json";
import places from "./places.json";
import religion from "./religion.json";
import school from "./school.json";
import space from "./space.json";
import time from "./time.json";
import vehicles from "./vehicles.json";

// ── Catalogue map ─────────────────────────────────────────────────────────────
export const CATEGORY_MODULES: Record<string, CategoryModule> = {
  "actions": actions as unknown as CategoryModule,
  "activities": activities as unknown as CategoryModule,
  "animals": animals as unknown as CategoryModule,
  "chat": chat as unknown as CategoryModule,
  "christmas": christmas as unknown as CategoryModule,
  "community": community as unknown as CategoryModule,
  "core-general": coreGeneral as unknown as CategoryModule,
  "core-joining-words": coreJoiningWords as unknown as CategoryModule,
  "core-letters": coreLetters as unknown as CategoryModule,
  "core-numbers": coreNumbers as unknown as CategoryModule,
  "core-position-words": corePositionWords as unknown as CategoryModule,
  "core-pronouns": corePronouns as unknown as CategoryModule,
  "core-time": coreTime as unknown as CategoryModule,
  "descriptions": descriptions as unknown as CategoryModule,
  "dinosaurs": dinosaurs as unknown as CategoryModule,
  "diwali": diwali as unknown as CategoryModule,
  "dropbar-core": dropbarCore as unknown as CategoryModule,
  "feelings": feelings as unknown as CategoryModule,
  "food-drink": foodDrink as unknown as CategoryModule,
  "fun": fun as unknown as CategoryModule,
  "health": health as unknown as CategoryModule,
  "home": home as unknown as CategoryModule,
  "nature": nature as unknown as CategoryModule,
  "numbers": numbers as unknown as CategoryModule,
  "people": people as unknown as CategoryModule,
  "places": places as unknown as CategoryModule,
  "religion": religion as unknown as CategoryModule,
  "school": school as unknown as CategoryModule,
  "space": space as unknown as CategoryModule,
  "time": time as unknown as CategoryModule,
  "vehicles": vehicles as unknown as CategoryModule,
};
