/**
 * ListModule catalogue barrel (ADR-014 §1). AUTO-GENERATED by
 * scripts/convert-packs-to-modules.mjs and the curation publish route — add
 * modules by dropping <slug>.json here and re-running, not by hand-editing.
 */

import type { ListModule } from "../_shared/types";

// ── Module imports ────────────────────────────────────────────────────────────
import christmas from "./christmas.json";
import dinosaurs from "./dinosaurs.json";
import diwali from "./diwali.json";
import fun from "./fun.json";
import religion from "./religion.json";
import testBedtime from "./test-bedtime.json";

// ── Catalogue map ─────────────────────────────────────────────────────────────
export const LIST_MODULES: Record<string, ListModule> = {
  "christmas": christmas as ListModule,
  "dinosaurs": dinosaurs as ListModule,
  "diwali": diwali as ListModule,
  "fun": fun as ListModule,
  "religion": religion as ListModule,
  "test-bedtime": testBedtime as ListModule,
};
