/**
 * ListModule catalogue barrel (ADR-014 §1). AUTO-GENERATED by
 * scripts/export-library-modules.mjs — these JSON files are the git
 * backup/restore artifact for the libraryModules table, NOT the live source.
 * Regenerate by re-running the exporter, not by hand-editing.
 */

import type { ListModule } from "../_shared/types";

// ── Module imports ────────────────────────────────────────────────────────────
import foodRoutines from "./food-routines.json";
import goingPlaces from "./going-places.json";
import lifeSkills from "./life-skills.json";
import selfHelp from "./self-help.json";

// ── Catalogue map ─────────────────────────────────────────────────────────────
export const LIST_MODULES: Record<string, ListModule> = {
  "food-routines": foodRoutines as ListModule,
  "going-places": goingPlaces as ListModule,
  "life-skills": lifeSkills as ListModule,
  "self-help": selfHelp as ListModule,
};
