/**
 * `/api/admin/language-publish` — Phase 8.1.
 *
 * Writes a new language module JSON to
 * `convex/data/languages/<code>.json` on disk and regenerates the
 * `_index.ts` barrel so the new language is wired into the registry on the
 * next bundle. Mirrors `/api/admin/pack-publish` exactly (Phase 6 of
 * ADR-010) — same dev-only guard, same barrel rebuild pattern.
 *
 * **Local-dev-only.** Writing to a repo file requires Node `fs/promises`
 * access to the working tree, which only works when `pnpm dev` is running
 * on a developer's machine. Returns 403 in any other environment. After
 * the file lands, the admin commits + redeploys to ship the new language.
 *
 * The publish lifecycle (when it goes live, whether it's beta/stable) is
 * the separate `languageLifecycle` row — write that via
 * `mutation languages.updateLanguageLifecycle`, not this route.
 *
 * Auth: Clerk-authenticated admin. The Convex `requireCallerIsAdmin` gate
 * also enforces on the lifecycle row.
 *
 * Returns: `{ ok: true, code, action: 'created' | 'updated' }` on success,
 * or 4xx with `{ error: string }`.
 */

import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { writeFile, mkdir, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

export const dynamic = "force-dynamic";

const REPO_ROOT = process.cwd();
const LANGUAGES_DIR = join(REPO_ROOT, "convex", "data", "languages");
const INDEX_PATH = join(LANGUAGES_DIR, "_index.ts");

function isDevEnvironment(): boolean {
  if (process.env.NODE_ENV !== "development") return false;
  if (process.env.DISABLE_LANGUAGE_PUBLISH === "true") return false;
  return true;
}

/** Convert an ISO code into a JS identifier safe for the barrel imports. */
function importVarFor(code: string): string {
  return code.replace(/[^a-zA-Z0-9]+/g, "_");
}

/**
 * Re-scan `convex/data/languages/` for `*.json` files and rebuild
 * `_index.ts` to match. Pure regen — avoids stale state if a file was
 * added or removed by hand between publishes.
 *
 * `en` and `hi` are kept first (legacy ordering); the rest sort
 * alphabetically by code.
 */
async function rebuildBarrel(): Promise<{ codes: string[] }> {
  const entries = await readdir(LANGUAGES_DIR);
  const codes = entries
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""))
    .sort((a, b) => {
      // Legacy ordering: en first, then hi, then alphabetical for the rest.
      const rank = (c: string) => (c === "en" ? 0 : c === "hi" ? 1 : 2);
      const ra = rank(a);
      const rb = rank(b);
      if (ra !== rb) return ra - rb;
      return a.localeCompare(b);
    });

  const importLines = codes.map(
    (code) => `import ${importVarFor(code)} from "./${code}.json";`
  );
  const arrayLines = codes.map(
    (code) => `  ${importVarFor(code)} as LangModule,`
  );

  const barrel = `/**
 * Typed barrel for language plugin modules — see ADR-009 §1, ADR-011 §3.
 *
 * Each language ships as a self-contained JSON module at
 * \`convex/data/languages/<code>.json\`. The runtime registry
 * (\`lib/languages/registry.ts\`) imports \`LANGUAGE_MODULES\` from here
 * and assembles a typed \`LangEntry[]\`, joining it with the
 * \`languageLifecycle\` table for status / publishedAt / expiresAt.
 *
 * Adding a language:
 *   1. Drop a new \`<code>.json\` matching \`LangModule\`
 *   2. Import + export it here
 *   3. Insert a \`languageLifecycle\` row (admin Languages section, Phase 8.1)
 *
 * The admin "Add language" flow (Phase 8.1) automates steps 1–3 via the
 * publish API route + Convex mutation; this file is the post-deploy
 * registration surface.
 *
 * This file is regenerated by \`/api/admin/language-publish\` on every
 * add.
 */

import type { LangModule } from "./types";

${importLines.join("\n")}

export const LANGUAGE_MODULES: readonly LangModule[] = [
${arrayLines.join("\n")}
];

export type { LangModule, LangStatus, VoiceEntry } from "./types";
`;

  await writeFile(INDEX_PATH, barrel);
  return { codes };
}

// ─── Input validation ───────────────────────────────────────────────────────

type LangModuleInput = {
  code: string;
  label: string;
  nativeLabel: string;
  dir: "ltr" | "rtl";
  font: string;
  voices: Array<{
    id: string;
    label: string;
    ttsVoiceId: string;
  }>;
};

function parseAndValidate(body: unknown): LangModuleInput {
  if (typeof body !== "object" || body === null) {
    throw new Error("Body must be a JSON object");
  }
  const b = body as Record<string, unknown>;

  const code = b.code;
  if (typeof code !== "string" || !/^[a-z]{2,3}(-[A-Z]{2})?$/.test(code)) {
    throw new Error(
      "`code` must be an ISO 639-1 code, optionally region-tagged (e.g. 'es', 'pt-BR')"
    );
  }
  const label = b.label;
  if (typeof label !== "string" || label.trim() === "") {
    throw new Error("`label` is required");
  }
  const nativeLabel = b.nativeLabel;
  if (typeof nativeLabel !== "string" || nativeLabel.trim() === "") {
    throw new Error("`nativeLabel` is required");
  }
  const dir = b.dir;
  if (dir !== "ltr" && dir !== "rtl") {
    throw new Error("`dir` must be 'ltr' or 'rtl'");
  }
  const font = b.font;
  if (typeof font !== "string" || font.trim() === "") {
    throw new Error("`font` is required");
  }
  // Voices may be empty at add-time; admin can add real voices in Phase 8.4.
  const voices = b.voices;
  if (!Array.isArray(voices)) {
    throw new Error("`voices` must be an array (can be empty)");
  }
  for (const v of voices) {
    if (typeof v !== "object" || v === null) throw new Error("voice entries must be objects");
    const vo = v as Record<string, unknown>;
    if (typeof vo.id !== "string") throw new Error("voice.id must be a string");
    if (typeof vo.label !== "string") throw new Error("voice.label must be a string");
    if (typeof vo.ttsVoiceId !== "string") throw new Error("voice.ttsVoiceId must be a string");
  }

  return { code, label, nativeLabel, dir, font, voices: voices as LangModuleInput["voices"] };
}

export async function POST(request: Request) {
  if (!isDevEnvironment()) {
    return NextResponse.json(
      {
        error:
          "Language publish is dev-only. Set NODE_ENV=development and unset DISABLE_LANGUAGE_PUBLISH to enable.",
      },
      { status: 403 }
    );
  }

  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  let mod: LangModuleInput;
  try {
    mod = parseAndValidate(body);
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Invalid body" },
      { status: 400 }
    );
  }

  if (!existsSync(LANGUAGES_DIR)) {
    await mkdir(LANGUAGES_DIR, { recursive: true });
  }

  const filePath = join(LANGUAGES_DIR, `${mod.code}.json`);
  const action = existsSync(filePath) ? "updated" : "created";

  await writeFile(filePath, JSON.stringify(mod, null, 2) + "\n");
  const { codes } = await rebuildBarrel();

  return NextResponse.json({
    ok: true,
    code: mod.code,
    action,
    catalogue: codes,
  });
}
