/**
 * PhraseModule catalogue barrel (ADR-014 §1). AUTO-GENERATED by
 * scripts/export-library-modules.mjs — these JSON files are the git
 * backup/restore artifact for the libraryModules table, NOT the live source.
 * Regenerate by re-running the exporter, not by hand-editing.
 */

import type { PhraseModule } from "../_shared/types";

// ── Module imports ────────────────────────────────────────────────────────────
// (none yet)

// ── Catalogue map ─────────────────────────────────────────────────────────────
export const PHRASE_MODULES: Record<string, PhraseModule> = {

};
